import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const publicDir = join(root, 'public');
const outputDir = join(root, 'dist-upload');

await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });

// 复制静态文件（保留原文件供非 Zip 场景使用）
for (const file of ['index.html', 'app.js', 'styles.css']) {
  await cp(join(publicDir, file), join(outputDir, file));
}

// 读取 API 核心逻辑
const apiHandler = await readFile(join(root, 'functions', 'api', '[[path]].js'), 'utf8');

// 读取静态文件并 base64 编码
const indexHtml = await readFile(join(publicDir, 'index.html'), 'utf8');
const appJs = await readFile(join(publicDir, 'app.js'), 'utf8');
const stylesCss = await readFile(join(publicDir, 'styles.css'), 'utf8');

const b64 = (s) => Buffer.from(s, 'utf8').toString('base64');

// 替换掉 env.ASSETS.fetch 分支，改为内嵌静态文件
const patchedApi = apiHandler.replace(
  "if (env?.ASSETS?.fetch) return env.ASSETS.fetch(request);\n    return new Response('Not Found', { status: 404 });",
  "return serveStatic(路径);"
);

const workerContent = `// Auto-generated by build-upload — embedded static files (base64)
const _f = {
  'index.html': '${b64(indexHtml)}',
  'app.js': '${b64(appJs)}',
  'styles.css': '${b64(stylesCss)}'
};
const _m = {
  'index.html': 'text/html; charset=utf-8',
  'app.js': 'application/javascript; charset=utf-8',
  'styles.css': 'text/css; charset=utf-8'
};
function serveStatic(path) {
  const name = path === '/' ? 'index.html' : path.slice(1);
  if (_f[name]) {
    return new Response(Uint8Array.from(atob(_f[name]), c => c.charCodeAt(0)), {
      status: 200,
      headers: { 'Content-Type': _m[name] || 'text/plain; charset=utf-8' }
    });
  }
  return new Response('Not Found', { status: 404 });
}
// --- API handler (patched) ---
${patchedApi}
`;

await writeFile(join(outputDir, '_worker.js'), workerContent, 'utf8');

console.log('Cloudflare local upload assets written to dist-upload/ (self-contained _worker.js)');
